feat: add side menu
Goodsurfing/gs-frontend pull request #25
Opened 2023-02-15 14:51 UTC by KuroMukade

2023-02-15 14:57 UTC, tntyyy requested changes

2023-02-15 14:57 UTC, tntyyy commented on src/components/SideMenu/SideMenu.tsx
> +        <div
отверстай не дивом, сделай aside или что то в таком духе

2023-02-15 14:57 UTC, tntyyy commented on src/styles/index.scss
> +	--color-black-tertiary: #484848;
третичный? может сделать third?

2023-02-15 14:57 UTC, tntyyy commented on src/components/SideMenu/SideMenuArrow/SideMenuArrow.tsx
> +    const boxClassname = cn(styles.box, {
пиши прямо в теге

2023-02-15 14:57 UTC, tntyyy commented on src/components/SideMenu/SideMenuArrow/SideMenuArrow.tsx
> +    const arrowClassname = cn({
пиши прямо в теге

2023-02-15 14:57 UTC, tntyyy commented on src/components/SideMenu/types/SideMenuArrow.interface.ts
> +    setOpened: (opeend: boolean) => void;
опечатка opeend

2023-02-15 14:57 UTC, tntyyy commented on src/components/SideMenu/types/SideMenuArrow.interface.ts
> +export { ISideMenuArrow }
смешной export, лучше сразу пиши export interface ...

2023-02-15 15:00 UTC, KuroMukade commented on src/components/SideMenu/types/SideMenuArrow.interface.ts
> +export { ISideMenuArrow }
смешной

2023-02-15 15:05 UTC, ignatiqq commented on src/components/SideMenu/SideMenu.tsx
> +    const [isOpen, setOpen] = useState<boolean>(false);
no need to type

2023-02-15 15:05 UTC, ignatiqq commented on src/components/SideMenu/SideMenu.tsx
> +            style={{ backgroundColor: theme }}
why? upper you have classanames for that

2023-02-15 15:05 UTC, ignatiqq commented on src/components/SideMenu/SideMenuArrow/SideMenuArrow.module.scss
> +    -khtml-user-select: none;
?

2023-02-15 15:05 UTC, ignatiqq commented on src/components/SideMenu/SideMenuArrow/SideMenuArrow.tsx
> +            onClick={() => setOpened(!opened)}
lets use callback in component for that

2023-02-15 15:05 UTC, ignatiqq commented on src/pages/ProfilePages/ProfilePage/ProfilePage.tsx
> +    // );
?

2023-02-16 14:58 UTC, tntyyy approved these changes

2023-02-16 14:58 UTC, tntyyy commented on src/components/SideMenu/SideMenuNavbar/SideMenuItem/SideMenuItem.tsx
> +                <img className={styles.img} src={icon} alt={text + " icon"} />
react ругается на слова image, icon, photo в alt.
представь лицо слабовидящего человека который услышит "фотография"

2023-02-16 14:58 UTC, tntyyy commented on src/components/SideMenu/SideMenuNavbar/SideMenuNavbar.tsx
> +                />
`
<SideMenuItem {...item} key={index} opened={opened} theme={theme} />
просто лаконичнее
`
+ я бы все же переименовал opened в isOpen, обычно именно так именуют булевы значения

2023-02-16 15:01 UTC, tntyyy approved these changes

2023-02-16 15:01 UTC, tntyyy commented on src/pages/ProfilePages/ProfilePage/ProfilePage.tsx
> +    return (<SideMenu theme='LIGHT' content={SideMenuData} />)
вынеси темы LIGHT и DARK в отдельный ENUM. и потом используй их как константы вместо строковых значений. 
например: SideMenuThemeEnum.DARK

2023-02-17 08:16 UTC, merged